package com.synergisticit.domain;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import jakarta.validation.constraints.NotEmpty;
import lombok.*;

@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
//@ToString
@DynamoDBTable(tableName = "users")
public class User {

    @DynamoDBHashKey
    private String userID;

    @NotEmpty
    private String userName;

    @NotEmpty
    private String role;


}


