package com.synergisticit.domain;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotEmpty;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
//@ToString
@DynamoDBTable(tableName = "users")
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userID;

    @NotEmpty
    private String userName;

    @NotEmpty
    private String password;

    @Email
    @NotEmpty
    private String email;



}
